# Generated by Django 3.1.7 on 2021-03-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_bancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('cuenta_banco', models.IntegerField()),
                ('banco', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_personales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('numero_registro', models.IntegerField()),
                ('vigencia', models.DateTimeField()),
                ('estado', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('promedio', models.FloatField(null=True)),
                ('cantidad_votos', models.IntegerField(null=True)),
                ('image_url', models.CharField(max_length=2083, null=True)),
                ('nombre_lugar_trabajo', models.CharField(max_length=255, null=True)),
                ('horario_inicio', models.IntegerField(null=True)),
                ('horario_fin', models.IntegerField(null=True)),
                ('direccion_trabajo', models.CharField(max_length=255, null=True)),
                ('latitud_trabajo', models.FloatField(null=True)),
                ('longitud_trabajo', models.FloatField(null=True)),
                ('lugares_libres', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('fecha_mov', models.FloatField()),
                ('monto', models.IntegerField()),
                ('origen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField()),
                ('puntuacion', models.FloatField()),
                ('comentarios', models.CharField(max_length=255)),
                ('reclamos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Woow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('foto', models.CharField(max_length=2083)),
            ],
        ),
    ]
