# Generated by Django 3.1.7 on 2021-03-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos_bancarios',
            new_name='DatosBancarios',
        ),
        migrations.RenameModel(
            old_name='Datos_personales',
            new_name='DatosPersonales',
        ),
    ]
