# Generated by Django 3.1.7 on 2021-03-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0002_auto_20210314_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosBancarios',
        ),
        migrations.DeleteModel(
            name='DatosPersonales',
        ),
        migrations.DeleteModel(
            name='Monedero',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
        migrations.DeleteModel(
            name='Woow',
        ),
    ]
