# Generated by Django 3.1.7 on 2021-03-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0004_conductor_hero_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductor',
            old_name='usr',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='id',
        ),
        migrations.AddField(
            model_name='conductor',
            name='idconductor',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conductor',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
