# Generated by Django 3.1.7 on 2021-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0005_auto_20210328_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('ci_operador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('tipo_operador', models.CharField(max_length=20)),
                ('id_lugar_asignado', models.IntegerField()),
                ('hora_inicio_trabajo', models.IntegerField()),
                ('Hora_fin_trabajo', models.IntegerField()),
                ('calificacion_promedio', models.IntegerField()),
            ],
        ),
    ]
