# Generated by Django 3.1.7 on 2021-03-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0007_lugaresdetrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('texto_denuncia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Propinas',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDenuncia',
            fields=[
                ('id_tipo_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
