# Generated by Django 3.1.7 on 2021-03-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0008_denuncia_propinas_tipodenuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id_comercio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OcuparLugar',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('ci_operado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.operador')),
                ('id_Lugar_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.lugaresdetrabajo')),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('id_comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.comercio')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='id_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlc.ocuparlugar'),
        ),
    ]
